default: &default
  adapter: postgresql
  encoding: unicode
  pool: 12
  template: template0

development:
  <<: *default
  database: coronavirus_find_support_form_development
  url: <%= ENV["DATABASE_URL"]%>

test:
  <<: *default
  database: coronavirus_find_support_form_test
  url: <%= ENV["TEST_DATABASE_URL"] %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"]%>
